type Deck {
  deckId: ID!
  name: String!
  userId: ID!
}

type Card {
  cardId: ID!
  deckId: ID!
  text: String!
  textTranslation: String!
  weight: Int!
}

type Query {
  hello: String
  getDecks(userId: ID!): [Deck!]!
  getDeck(userId: ID!, deckId: ID!): Deck!
  getCardsForDeck(userId: ID!, deckId: ID!): [Card!]!
}

type Mutation {
  createDeck(userId: ID!, name: String!): Deck!
  addCard(userId: ID!, deckId: ID!, text: String!, textTranslation: String!): Card!
  deleteDeck(userId: ID!, deckId: ID!): ID!
  deleteCard(userId: ID!, deckId: ID!, cardId: ID!): ID!
  updateCard(userId: ID!, deckId: ID!, cardId: ID!, text: String!, textTranslation: String!): Card!
}
